export const firewallGeoSourceProviderOptions = [
  { title: 'JSON / SagerNet Github', value: 'json.sagernet_github' },
  { title: 'JSON / SagerNet CDN', value: 'json.sagernet_cdn' },
  { title: 'JSON / KaringX Github', value: 'json.karingx_github' },
  { title: 'JSON / KaringX CDN', value: 'json.karingx_cdn' },
  { title: 'JSON / Loyalsoldier_IP Github', value: 'json.loyalsoldier_ip_github' },
  { title: 'JSON / Loyalsoldier_IP CDN', value: 'json.loyalsoldier_ip_cdn' },
  { title: 'JSON / QuixoticHeart Github', value: 'json.quixoticheart_github' },
  { title: 'JSON / MetaCubeX Github', value: 'json.metacubex_github' },
  { title: 'JSON / MetaCubeX CDN', value: 'json.metacubex_cdn' },
  { title: 'JSON / Chocolate4U Github', value: 'json.chocolate4u_github' },
  { title: 'JSON / Chocolate4U CDN', value: 'json.chocolate4u_cdn' },
  { title: 'JSON / lyc8503 Github', value: 'json.lyc8503_github' },
  { title: 'JSON / lyc8503 CDN', value: 'json.lyc8503_cdn' },
  { title: 'JSON / lyc8503 CDN 1', value: 'json.lyc8503_cdn1' },
  { title: 'Clash / MetaCubeX Github', value: 'clash.metacubex_github' },
  { title: 'Clash / MetaCubeX CDN', value: 'clash.metacubex_cdn' },
  { title: 'Clash / QuixoticHeart Github', value: 'clash.quixoticheart_github' },
  { title: 'Clash / Loyalsoldier_IP Github', value: 'clash.loyalsoldier_ip_github' },
  { title: 'Clash / Loyalsoldier_IP CDN', value: 'clash.loyalsoldier_ip_cdn' },
]

export const firewallGeoCountryCodeOptions = [
  'PRIVATE',
  'US',
  'JP',
  'CN',
  'HK',
  'TW',
  'SG',
  'KR',
  'IN',
  'ID',
  'MY',
  'TH',
  'VN',
  'PH',
  'IR',
  'TR',
  'AE',
  'SA',
  'DE',
  'FR',
  'GB',
  'IT',
  'ES',
  'NL',
  'BE',
  'CH',
  'SE',
  'NO',
  'FI',
  'DK',
  'PL',
  'RU',
  'UA',
  'CA',
  'MX',
  'BR',
  'AR',
  'CL',
  'AU',
  'NZ',
  'ZA',
  'EG',
  'NG',
]
